### ISSUE TITLE
token symbols - append `d` for wrapped tokens and update logos

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/wallet#555] opened 2021-08-12 23:33 UTC
#### What would you like to be added:

- [x] For all wrapped tokens that we have, add a prefix 'd' to differentiate wrapped and native tokens for atomic swap
- [x] Update icons for wrapped tokens (Lighter) @jtlntno-cake  to provide new tokens

#### Why is this needed:
![image](https://user-images.githubusercontent.com/25013382/129282925-ed608ad5-e108-47b5-a6db-00f357f7ce9d.png)

**Comment by ivan-zynesis** [comment] 2021-08-24 09:52
@fullstackninja864 Another request, maybe can be done together with this issue.

```ts
const mapping: Record<AssetName, (props: SvgProps) => JSX.Element> = { ... }
export function getNativeIcon (symbol: AssetName): (props: SvgProps) => JSX.Element { ... }
```

**Comment by thedoublejay** [comment] 2021-08-24 10:15
@ivan-zynesis is this for the icon? If yes, we have added it already during launch

**Comment by ivan-zynesis** [comment] 2021-08-24 10:18
> @ivan-zynesis is this for the icon? If yes, we have added it already during launch

Do we? I mean the give specific type for token, so if we want to use raw string, have to cast it
`getNativeIcon(symbol as AssetName) // if symbol is a simple string`

**Comment by ivan-zynesis** [comment] 2021-08-24 10:20
My request is only make sense if Harsh's approach to tackle the issue is auto prepend `d` only each token + auto differentiate which icon to return XXX (return normal), dXXX (return the wrapped one). Feel free to ignore it if that's the way going to be implemented.

**Comment by thedoublejay** [comment] 2021-08-24 10:49
Ahhh yes I think Fuxing already added this validation on the icon method.

**Comment by fuxingloh** [comment] 2021-08-25 08:37
Is there a render for of this on Dex page, I wonder how it will look like

**Comment by fullstackninja864** [comment] 2021-08-25 08:40
Its bit messed up but it will look like this 
![image](https://user-images.githubusercontent.com/53080940/130758063-30e5c74d-a2d2-4b62-8563-8daa5bcc3d83.png)

**Comment by thedoublejay** [comment] 2021-08-25 08:47
Will be done on Whale side - https://github.com/DeFiCh/whale/issues/361

**Comment by fullstackninja864** [comment] 2021-08-25 09:12
Will create Pr for Balance screen @thedoublejay

**Comment by thedoublejay** [comment] 2021-08-25 09:17
@fullstackninja864 actually this one should be handled on Whale as well. Both poolpairs and token list

**Comment by fullstackninja864** [comment] 2021-08-25 09:21
Ok @thedoublejay  Will be closing this PR without merge then

**Comment by thedoublejay** [comment] 2021-09-01 01:50
@fullstackninja864 after this has been merged, you can proceed with this linked issue - https://github.com/DeFiCh/wallet/issues/717

**Comment by fullstackninja864** [comment] 2021-09-01 06:59
@thedoublejay for token listing api `/address/<address>/tokens`
response 
```
{
  "data": [
    {
      "id": "0",
      "amount": "10.52258000",
      "symbol": "DFI",
      "symbolKey": "DFI",
      "name": "Default Defi token",
      "isDAT": true,
      "isLPS": false
    },
    {
      "id": "2",
      "amount": "5.00000000",
      "symbol": "ETH",
      "symbolKey": "ETH",
      "name": "Playground ETH",
      "isDAT": true,
      "isLPS": false
    },
    {
      "id": "7",
      "amount": "0.50000000",
      "symbol": "DFI-ETH",
      "symbolKey": "DFI-ETH",
      "name": "Default Defi token-Playground ETH",
      "isDAT": true,
      "isLPS": true
    }
  ]
}
```
which dosen't contain display symbol attribute, I guess This should also get handled in Whale

**Closed** 2021-09-07 07:39 UTC
Labels: triage/accepted, kind/feature, area/ui-ux
